### ISSUE TITLE
Cannot find module 'xo' or its corresponding type declarations.

### ISSUE THREAD

**Issue by ozum** [rocktimsaikia/read-git-user#6]
Hi,

When used with typescript (v3 and v4), I got following error:

```
node_modules/read-git-user/index.d.ts:1:23 - error TS2307: Cannot find module 'xo' or its corresponding type declarations.

1 import {Options} from 'xo';
                        ~~~~
```

Also it seems, `xo` is not used here. Removing this line corrects the error.

Thanks,

**Comment by rocktimsaikia** [comment]
Yes, you are right. 

>  import {Options} from 'xo';

I don't remember adding this line to the module. This might have been added by my IDE auto-complete feature without me noticing it. PRs are welcome on this :+1:

**Comment by ozum** [comment]
Sent PR.
